# -*- coding: utf-8 -*-
"""SOC_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d02oT4ChFRA_AiFLtVKC4y1Ittxinmy5
"""

#WEEK 1 ASSIGNMENT

import numpy as np


# Code to generate n datapoints, returns an np array of n numbers ranging from 0
# to 10000
def data(n):
	x = np.random.randint(10001, size = n) # np ke andar random library ke andar randint function hai
	return x

x = data(10)
print(x)

# find the mean, median, mode, sum, variance, and standard deviation 
import statistics as st
#print("mean:", 2)
print("Mean: ", st.mean(x))
print("Median:", st.median(x))
print("Mode:", st.mode(x))
print("Sum: ", sum(x))
print("Variance: ", st.variance(x))
print("Standard Deviation: ", st.stdev(x))

# quicksort
def quicksort(x):
  # returns sorted list
  # base case
  if len(x) == 0:
    return []
  if len(x) == 1:
    return x # not x[0] as it will return 0th element but we want [0th element]
  a = x[0] # x[len(x)-1] for last element
  x1 = []
  x2 = []
  for i in range(1, len(x)):
    if x[i]<a:
      x1.append(x[i])
    else:
      x2.append(x[i])
  x1 = quicksort(x1)
  x2 = quicksort(x2)
  return x1+[a]+x2

print("Data: ")
print(x)
y = quicksort(x)
print("After quicksorting: ")
print(y)